version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudops-dev"
s3_prefix = "cloudops"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=\"dev\" FrontendBucketName=\"cloudops-frontend\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "cloudops-prod"
s3_prefix = "cloudops-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=\"prod\" FrontendBucketName=\"cloudops-frontend\""
